### ISSUE TITLE
`netcomp` not working properly

### ISSUE THREAD

**Issue by barneydobson** [ImperialCollegeLondon/SWMManywhere#290]
Assuming have copied [config](https://imperialcollegelondon.github.io/SWMManywhere/config_guide/#minimum-viable-configuration) and updated accordingly. @dalonsoa it'd be amazing if you could take a look please.

```bash
python -m venv ./sa_env
./sa_env/Scripts/activate.bat
pip install swmmanywhere
python -m swmmanywhere --config_path=minimum_viable_template.yml 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\bdobson\Downloads\temp\sa_env\Lib\site-packages\swmmanywhere\__main__.py", line 8, in <module>
    from swmmanywhere import swmmanywhere
  File "C:\Users\bdobson\Downloads\temp\sa_env\Lib\site-packages\swmmanywhere\swmmanywhere.py", line 22, in <module>
    from swmmanywhere.metric_utilities import iterate_metrics, validate_metric_list
  File "C:\Users\bdobson\Downloads\temp\sa_env\Lib\site-packages\swmmanywhere\metric_utilities.py", line 21, in <module>
    import netcomp
ModuleNotFoundError: No module named 'netcomp'
```

**Comment by dalonsoa** [comment]
It seems that `netcomp` was included in the source application but not in the wheel, so when installed from PyPI, it is not there. Let's see what I need to do to make that happen. This will require another release, I'm affraid, and mark the previous one as `wrong`, so no one installs it.

**Comment by barneydobson** [comment]
OK great thanks - how do I mark as `wrong`?

**Comment by barneydobson** [comment]
closed by #293

**Comment by cheginit** [comment]
@barneydobson make sure to yank the release. Can be done by the manager of the package on https://pypi.org/ which I think is @dalonsoa?

**Comment by barneydobson** [comment]
I think @dalonsoa did 👍

**Comment by barneydobson** [comment]
@dalonsoa new bug with the distribution:

```
Run if [[ "false" != 'true' ]]; then
/tmp/baipp/dist/swmmanywhere-0.1.2-py3-none-any.whl: W009: Wheel contains multiple toplevel library entries:
  netcomp/
  swmmanywhere/
Error: Process completed with exit code 1.
```

**Comment by cheginit** [comment]
You need to move the `netcomp` folder under `swmmanywhere` as a subpackage.

**Comment by dalonsoa** [comment]
I've just seen it, but I don't understand why that is a problem. The wheel works and it is not uncommon to distribute multiple packages together. If we move `netcomp` to within `swmmanywhere`, we need to change all of import statements for `netcomp`.

**Comment by barneydobson** [comment]
looking at [examples](https://github.com/pypa/hatch/discussions/1050) - could we move both into `src`?

**Comment by dalonsoa** [comment]
That's what I was starting to think, to be honest.

**Comment by cheginit** [comment]
I second the src-layout (I use it for all my projects). You have to make a couple of changes to `pyproject.toml` for `hatchling`, `pytest`, and `coverage`.

**Comment by dalonsoa** [comment]
On it...

**Comment by barneydobson** [comment]
OK still failing: https://github.com/ImperialCollegeLondon/SWMManywhere/actions/runs/11036163538/job/30654221348

I guess we're not fixing this today - but any ideas from @cheginit or @dalonsoa are welcome!

**Comment by barneydobson** [comment]
( I will first try the suggestion [here](https://github.com/pypa/hatch/discussions/1050) )
