### ISSUE TITLE
GitHub pre-commit is automerging

### ISSUE THREAD

**Issue by barneydobson** [ImperialCollegeLondon/SWMManywhere#323]
If pre-commit detects fixable errors, it will fix them, GitHub actions bot will commit those changes, and then the PR is a candidate for auto-merge.

Not sure this is ideal!

Tagging @dalonsoa since I think you implemented/suggested some of these bits.

**Comment by dalonsoa** [comment]
That's... an interesting point. We hadn't spotted that elsewhere. Let me check with the rest of the team.

**Comment by dalonsoa** [comment]
Ok, it seems that has bitten us in the past. The key is to check who opened the PR, rather than who authored the last commit, as done here: https://github.com/ImperialCollegeLondon/python-template/blob/28bee6e394dd749f1227d0df23171b4a1a3fcafa/.github/workflows/auto-merge.yml#L13
