### ISSUE TITLE
Seems to require `setuptools` 

### ISSUE THREAD

**Issue by barneydobson** [ImperialCollegeLondon/SWMManywhere#329]
Ubuntu for python 3.12
Caused by CDSAPI (which can be binned anyway)

Fails on the Quickstart minimum viable run

not sure why `setuptools` is causing an issue, I thought `hatchling` removed need it

**Comment by AdrianDAlessandro** [comment]
Looking into reproducing this

**Comment by AdrianDAlessandro** [comment]
I could not reproduce this bug locally or in CI (see #332)

**Comment by barneydobson** [comment]
#332 demonstrates that it's not a ubuntu + 3.12 issue. My only thought is that it could be related to the CLI call, so I will mention it there and close this issue
